// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate():Promise<Record<string, any>>;

export function CheckForUpdate():Promise<Record<string, any>>;

export function DownloadUpdate():Promise<Record<string, any>>;

export function GetPendingRelease():Promise<Record<string, any>>;

export function GetVersionInfo():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function Version():Promise<string>;
