// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['app']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function GetPendingRelease() {
  return window['go']['app']['App']['GetPendingRelease']();
}

export function GetVersionInfo() {
  return window['go']['app']['App']['GetVersionInfo']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
